site_name: Plateforme de documentation en Géomatique

theme:
  name: readthedocs

nav:
  - Accueil: index.md
  - Le viatique des Adolescents: tazawoudous_sikhar.md

extra_css:
  - css/le_style.css

















