site_name: Apprendre les enseignements islamiques de Cheikh Ahmadou Bamba Mbacké 
theme:
  name: readthedocs

nav:
  - Accueil: index.md
  - Le viatique des Adolescents: tazawoudous_sikhar.md
  - Les itinéraires du paradis: massalik.md
  - (Jurisprudence: jawharu_nafis

extra_css:
  - css/le_style.css




















