site_name: Apprendre les enseignements islamiques de Cheikh Ahmadou Bamba Mbacké 
theme:
  name: readthedocs

nav:
  - Accueil: index.md
  - SAINT CORAN: alxuraane.md
  - Arbre généalogique des figures historiques: arbre_genealogique.md
  - Le viatique des Adolescents: tazawoudous_sikhar.md
  - Les itinéraires du paradis: massalik.md
  - Jurisprudence: jawharu_nafis.md
  - La voie de la satisfaction des besoins: nahju.md
  - Famille de l'auteur du site: famille_arbre_genealogique.md
  - Wolofal Xarnu bi: xarnu_bi.md
extra_css:
  - css/le_style.css





















